apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-team-1
  labels:
    app: ws-team-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-team-1
  template:
    metadata:
      labels:
        app: ws-team-1
    spec:
      containers:
        - name: ws-monolith
          image: WsTeam1:TAG
          ports:
            - containerPort: 80

